USE HotelDW;

ALTER TABLE DimGuest
ALTER COLUMN name VARCHAR(200);

ALTER TABLE DimGuest
ALTER COLUMN email VARCHAR(200);

ALTER TABLE DimGuest
ALTER COLUMN phone_number VARCHAR(50);

ALTER TABLE DimGuest
ALTER COLUMN credit_card VARCHAR(50);

ALTER TABLE DimGuest
ALTER COLUMN country VARCHAR(50);

ALTER TABLE DimHotel
ALTER COLUMN hotel_name VARCHAR(100);

ALTER TABLE DimHotel
ALTER COLUMN hotel_type NVARCHAR(50);